#!/bin/bash

cd /home/teodoran/depot/speedtest-history

echo "New speedtest:" >> ./public/speedtest.log
date --iso-8601=minutes >> ./public/speedtest.log
speedtest-cli | grep "Hosted by*\|Download:*\|Upload:*" >> ./public/speedtest.log

git add ./public/speedtest.log &> /dev/null
git commit -m "Updating speedtest.log data" &> /dev/null
git push heroku master &> /dev/null